### ISSUE TITLE
Not really an issue, just an heads up

### ISSUE THREAD

**Issue by robcazzaro** [zuckschwerdt/PlutoSDR-Apps#1]
Not sure what is the proper etiquette when plagiarizing someone else's work (instead of cloning), so I thought I'd err on the side of disclosure.

I was trying to cross compile a few apps to run directly on PlutoSDR, and I was utterly lost until I found this repository. Which unfortunately didn't quite work "as is" for me. So I copied the files of interest and created a new repository here https://github.com/robcazzaro/PlutoSDR-Apps, making the necessary changes (and then some) 

Having interacted with you before (ANT protocol), I highly doubt you'd have any problems, but just in case... Thanks for having created this repository, was super helpful!

**Comment by zuckschwerdt** [comment]
Actually, I forgot to disable this repo. Maybe checkout the updated repo at https://github.com/triq-org/PlutoSDR-Apps/
